// Package report renders .planning/codebase/GRAPH_REPORT.md, the
// deterministic human-facing digest of a schemaVersion-5 map. Ported
// push-for-push from draht-tools.cjs visRenderReport (lines 5046-5096). No
// Date, no locale, no randomness: identical *model.Map in => identical
// bytes out.
package report

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/draht-dev/draht/go/internal/model"
)

// codeExtRe matches the CJS engine's code-file extension test
// (/\.(ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|rb|php|swift|kt|cs|c|cpp)$/),
// used to filter a cluster's members down to code files before rendering
// example members.
var codeExtRe = regexp.MustCompile(`\.(ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|rb|php|swift|kt|cs|c|cpp)$`)

// rationaleHighlightTags is the fixed filter set for the "Rationale
// highlights" section: {SECURITY, BUG, FIXME, HACK}. NOTE/WHY/TODO/PERF/etc.
// are deliberately dropped.
var rationaleHighlightTags = map[string]bool{
	"SECURITY": true,
	"BUG":      true,
	"FIXME":    true,
	"HACK":     true,
}

// Render returns the exact GRAPH_REPORT.md bytes for m. The result always
// ends with exactly one "\n" (the renderer's terminal empty line). Never
// returns an error: every field it reads is optional and has a documented
// zero-value path (nil slices behave as empty, a nil Languages counter
// renders "n/a", etc).
func Render(m *model.Map) []byte {
	var l []string
	push := func(lines ...string) { l = append(l, lines...) }

	stats := m.Stats
	langs := topLanguages(stats.Languages)

	push(fmt.Sprintf("# %s — Codebase Graph Report", m.Root), "")
	push("_Generated by `draht-tools map-graph`. Do not edit; regenerated each build._", "")
	push("## Overview")

	assetsTotal := m.Assets.Total
	assetsSuffix := ""
	if assetsTotal != 0 {
		assetsSuffix = fmt.Sprintf(" (+%d non-code files)", assetsTotal)
	}
	push(fmt.Sprintf(
		"%d code modules%s · %s LOC · %d packages · %d import edges · %d entry points · %d clusters.",
		stats.Files, assetsSuffix, commaGroup(stats.TotalLoc), stats.Packages, stats.Edges,
		stats.EntryPoints, len(m.Clusters),
	))
	push(fmt.Sprintf("Languages: %s.", langs), "")

	push("## Key concepts (structural neighborhoods)", "")
	push("> Clusters are import-topology neighborhoods, not semantic bounded contexts — confirm before treating them as such.", "")

	clusters := m.Clusters
	if len(clusters) > 8 {
		clusters = clusters[:8]
	}
	for _, c := range clusters {
		members := clusterMembers(c.Members)
		suffix := ""
		if members != "" {
			suffix = " · e.g. " + members
		}
		push(fmt.Sprintf("- **%s** — %d modules · %s%s", c.Label, c.Size, c.DominantLayer, suffix))
	}

	push("", "## God nodes (most connected)", "")
	push("| File | In | Out | Note |", "| --- | --- | --- | --- |")
	godNodes := m.Hotspots.GodNodes
	if len(godNodes) > 8 {
		godNodes = godNodes[:8]
	}
	for _, g := range godNodes {
		push(fmt.Sprintf("| `%s` | %d | %d | %s |", g.Path, g.InDegree, g.OutDegree, g.Reason))
	}

	sc := m.SurprisingConnections
	if len(sc) > 0 {
		push("", "## Surprising connections", "")
		capped := sc
		if len(capped) > 10 {
			capped = capped[:10]
		}
		for _, x := range capped {
			syms := x.SampleSymbols
			if len(syms) > 3 {
				syms = syms[:3]
			}
			symStr := strings.Join(syms, ", ")
			suffix := ""
			if symStr != "" {
				suffix = " · " + symStr
			}
			push(fmt.Sprintf("- `%s` → `%s` — %s (score %s)%s", x.From, x.To, x.Reason, jsNumber(x.Score), suffix))
		}
	}

	rh := filterRationale(m.RationaleIndex)
	if len(rh) > 0 {
		push("", "## Rationale highlights (SECURITY / BUG / FIXME / HACK)", "")
		for _, r := range rh {
			push(fmt.Sprintf("- **%s** `%s:%d` — %s", r.Tag, r.File, r.Line, r.Text))
		}
	}

	push("", "## Suggested questions", "")
	for _, q := range suggestedQuestions(m) {
		push("- " + q)
	}

	push("", "---",
		"Query the graph: `draht-tools graph-context <file>` · `graph-impact <file>` · `graph-query \"<concept>\"` · `graph-hotspots` · `graph-clusters --surprising`.",
		"")

	return []byte(strings.Join(l, "\n"))
}

// Write writes Render(m) to path with mode 0644, creating parent dirs.
// Callers gate on the MAP.json unchanged-check, exactly as visWriteOutputs
// does (the report is NOT regenerated when MAP.json is unchanged, even if
// the report file is missing).
func Write(path string, m *model.Map) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("report: mkdir %s: %w", dir, err)
	}
	if err := os.WriteFile(path, Render(m), 0o644); err != nil {
		return fmt.Errorf("report: write %s: %w", path, err)
	}
	return nil
}

// topLanguages returns the "typescript 1277, markdown 257, …" fragment:
// stats.languages minus "other", sorted count DESC then key ASC, capped at
// 6. Returns "n/a" when empty (or when c is nil).
func topLanguages(c *model.OrderedCounts) string {
	type kv struct {
		k string
		v int
	}
	var items []kv
	for _, k := range c.Keys() {
		if k == "other" {
			continue
		}
		items = append(items, kv{k, c.Get(k)})
	}
	sort.Slice(items, func(i, j int) bool {
		if items[i].v != items[j].v {
			return items[i].v > items[j].v
		}
		return items[i].k < items[j].k
	})
	if len(items) > 6 {
		items = items[:6]
	}
	if len(items) == 0 {
		return "n/a"
	}
	parts := make([]string, len(items))
	for i, it := range items {
		parts[i] = fmt.Sprintf("%s %d", it.k, it.v)
	}
	return strings.Join(parts, ", ")
}

// clusterMembers renders a cluster's " · e.g. `a/b`, `c/d`" fragment (code-
// extension filter with unfiltered fallback, cap 4, last-two-path-segments).
// Returns "" when there are no members, in which case the caller drops the
// whole " · e.g. " suffix.
func clusterMembers(members []string) string {
	code := make([]string, 0, len(members))
	for _, m := range members {
		if codeExtRe.MatchString(m) {
			code = append(code, m)
		}
	}
	src := code
	if len(src) == 0 {
		src = members
	}
	if len(src) > 4 {
		src = src[:4]
	}
	if len(src) == 0 {
		return ""
	}
	parts := make([]string, len(src))
	for i, m := range src {
		parts[i] = "`" + lastTwoSegments(m) + "`"
	}
	return strings.Join(parts, ", ")
}

// lastTwoSegments ports graphShort/m.split("/").slice(-2).join("/"): the
// last two "/"-separated path segments, or the whole string when it has one
// or two segments.
func lastTwoSegments(p string) string {
	parts := strings.Split(p, "/")
	if len(parts) <= 2 {
		return p
	}
	return strings.Join(parts[len(parts)-2:], "/")
}

// filterRationale keeps only {SECURITY, BUG, FIXME, HACK}-tagged entries, in
// their original order, capped at 12.
func filterRationale(entries []model.RationaleEntry) []model.RationaleEntry {
	var out []model.RationaleEntry
	for _, r := range entries {
		if !rationaleHighlightTags[r.Tag] {
			continue
		}
		out = append(out, r)
		if len(out) == 12 {
			break
		}
	}
	return out
}

// suggestedQuestions builds the 0-4 question lines plus the fallback line.
// Two of the four probes search their FULL, unsliced/unfiltered source
// (map.surprisingConnections for the bridge probe, map.rationaleIndex for
// the HACK/FIXME probe) rather than the already-capped lists rendered
// above — an entry can drive a question here even when it never appears in
// the report body. This mirrors the CJS renderer exactly; do not "fix" it
// by searching the capped lists.
func suggestedQuestions(m *model.Map) []string {
	var gq []string

	if godNodes := m.Hotspots.GodNodes; len(godNodes) > 0 {
		top := godNodes[0]
		gq = append(gq, fmt.Sprintf("Why does `%s` have %d dependents — is that coupling intended?", top.Path, top.InDegree))
	}

	for _, x := range m.SurprisingConnections {
		if strings.Contains(x.Reason, "bridge") {
			gq = append(gq, fmt.Sprintf("Is the bridge `%s` → `%s` intended, or accidental coupling?", x.From, x.To))
			break
		}
	}

	for _, r := range m.RationaleIndex {
		if r.Tag == "HACK" || r.Tag == "FIXME" {
			gq = append(gq, fmt.Sprintf("Should the %s at `%s:%d` be addressed? (\"%s\")", r.Tag, r.File, r.Line, r.Text))
			break
		}
	}

	if clusters := m.Clusters; len(clusters) > 0 {
		big := clusters[0]
		gq = append(gq, fmt.Sprintf("Cluster \"%s\" holds %d modules — should it be split?", big.Label, big.Size))
	}

	if len(gq) == 0 {
		gq = append(gq, "Run `draht-tools graph-hotspots` and `graph-clusters --surprising` to explore.")
	}
	return gq
}

// jsNumber formats a float64 the way JS template-literal interpolation of a
// Number does for the small integer/one-decimal scores this renderer sees
// (surprisingConnections[*].score): minimal digits, no trailing ".0" for
// whole numbers, no scientific notation in this value range.
func jsNumber(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

// commaGroup formats n with "," thousands separators (US-locale grouping),
// matching JS Number.prototype.toLocaleString() for the Overview line's LOC
// figure — the only number in the whole report that is grouped.
//
// This intentionally duplicates cmd/draht-tools/mapgraph.go's commaInt():
// this work package (go/internal/report, built in parallel with sibling
// work packages touching go/cmd and other internal/ dirs) is scoped to this
// directory only. The integrator should fold both call sites onto a single
// shared helper (e.g. internal/numfmt.Comma, as sketched in the phase-3
// design doc) once the parallel build lands.
func commaGroup(n int) string {
	neg := n < 0
	if neg {
		n = -n
	}
	s := strconv.Itoa(n)
	var out []byte
	for i := 0; i < len(s); i++ {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, s[i])
	}
	if neg {
		return "-" + string(out)
	}
	return string(out)
}
