// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/anthropic.json" with { type: "json" };

export const ANTHROPIC_MODELS: ChatModelCatalog<typeof values, "anthropic"> = flattenChatModelCatalog(
	"anthropic",
	values,
);

export const ANTHROPIC_IMAGE_MODELS: ImageModelCatalog<typeof values, "anthropic"> = flattenImageModelCatalog(
	"anthropic",
	values,
);

export const ANTHROPIC_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "anthropic"> =
	flattenClassifierModelCatalog("anthropic", values);
