// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/baseten.json" with { type: "json" };

export const BASETEN_MODELS: ChatModelCatalog<typeof values, "baseten"> = flattenChatModelCatalog("baseten", values);

export const BASETEN_IMAGE_MODELS: ImageModelCatalog<typeof values, "baseten"> = flattenImageModelCatalog(
	"baseten",
	values,
);

export const BASETEN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "baseten"> =
	flattenClassifierModelCatalog("baseten", values);
