// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/cerebras.json" with { type: "json" };

export const CEREBRAS_MODELS: ChatModelCatalog<typeof values, "cerebras"> = flattenChatModelCatalog("cerebras", values);

export const CEREBRAS_IMAGE_MODELS: ImageModelCatalog<typeof values, "cerebras"> = flattenImageModelCatalog(
	"cerebras",
	values,
);

export const CEREBRAS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "cerebras"> =
	flattenClassifierModelCatalog("cerebras", values);
