// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";
import values from "./data/deepseek.json" with { type: "json" };

export const DEEPSEEK_MODELS = values as {
	"deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-v4-flash";
		provider: "deepseek";
	};
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "deepseek";
	};
};
