// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/deepseek.json" with { type: "json" };

export const DEEPSEEK_MODELS: ChatModelCatalog<typeof values, "deepseek"> = flattenChatModelCatalog("deepseek", values);

export const DEEPSEEK_IMAGE_MODELS: ImageModelCatalog<typeof values, "deepseek"> = flattenImageModelCatalog(
	"deepseek",
	values,
);

export const DEEPSEEK_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "deepseek"> =
	flattenClassifierModelCatalog("deepseek", values);
