// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/fireworks.json" with { type: "json" };

export const FIREWORKS_MODELS: ChatModelCatalog<typeof values, "fireworks"> = flattenChatModelCatalog(
	"fireworks",
	values,
);

export const FIREWORKS_IMAGE_MODELS: ImageModelCatalog<typeof values, "fireworks"> = flattenImageModelCatalog(
	"fireworks",
	values,
);

export const FIREWORKS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "fireworks"> =
	flattenClassifierModelCatalog("fireworks", values);
