// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/github-copilot.json" with { type: "json" };

export const GITHUB_COPILOT_MODELS: ChatModelCatalog<typeof values, "github-copilot"> = flattenChatModelCatalog(
	"github-copilot",
	values,
);

export const GITHUB_COPILOT_IMAGE_MODELS: ImageModelCatalog<typeof values, "github-copilot"> = flattenImageModelCatalog(
	"github-copilot",
	values,
);

export const GITHUB_COPILOT_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "github-copilot"> =
	flattenClassifierModelCatalog("github-copilot", values);
