// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/google-vertex.json" with { type: "json" };

export const GOOGLE_VERTEX_MODELS: ChatModelCatalog<typeof values, "google-vertex"> = flattenChatModelCatalog(
	"google-vertex",
	values,
);

export const GOOGLE_VERTEX_IMAGE_MODELS: ImageModelCatalog<typeof values, "google-vertex"> = flattenImageModelCatalog(
	"google-vertex",
	values,
);

export const GOOGLE_VERTEX_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "google-vertex"> =
	flattenClassifierModelCatalog("google-vertex", values);
