// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/google.json" with { type: "json" };

export const GOOGLE_MODELS: ChatModelCatalog<typeof values, "google"> = flattenChatModelCatalog("google", values);

export const GOOGLE_IMAGE_MODELS: ImageModelCatalog<typeof values, "google"> = flattenImageModelCatalog(
	"google",
	values,
);

export const GOOGLE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "google"> = flattenClassifierModelCatalog(
	"google",
	values,
);
