// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/huggingface.json" with { type: "json" };

export const HUGGINGFACE_MODELS: ChatModelCatalog<typeof values, "huggingface"> = flattenChatModelCatalog(
	"huggingface",
	values,
);

export const HUGGINGFACE_IMAGE_MODELS: ImageModelCatalog<typeof values, "huggingface"> = flattenImageModelCatalog(
	"huggingface",
	values,
);

export const HUGGINGFACE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "huggingface"> =
	flattenClassifierModelCatalog("huggingface", values);
