// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/kimi-coding.json" with { type: "json" };

export const KIMI_CODING_MODELS: ChatModelCatalog<typeof values, "kimi-coding"> = flattenChatModelCatalog(
	"kimi-coding",
	values,
);

export const KIMI_CODING_IMAGE_MODELS: ImageModelCatalog<typeof values, "kimi-coding"> = flattenImageModelCatalog(
	"kimi-coding",
	values,
);

export const KIMI_CODING_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "kimi-coding"> =
	flattenClassifierModelCatalog("kimi-coding", values);
