// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/minimax-cn.json" with { type: "json" };

export const MINIMAX_CN_MODELS: ChatModelCatalog<typeof values, "minimax-cn"> = flattenChatModelCatalog(
	"minimax-cn",
	values,
);

export const MINIMAX_CN_IMAGE_MODELS: ImageModelCatalog<typeof values, "minimax-cn"> = flattenImageModelCatalog(
	"minimax-cn",
	values,
);

export const MINIMAX_CN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "minimax-cn"> =
	flattenClassifierModelCatalog("minimax-cn", values);
