// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/mistral.json" with { type: "json" };

export const MISTRAL_MODELS: ChatModelCatalog<typeof values, "mistral"> = flattenChatModelCatalog("mistral", values);

export const MISTRAL_IMAGE_MODELS: ImageModelCatalog<typeof values, "mistral"> = flattenImageModelCatalog(
	"mistral",
	values,
);

export const MISTRAL_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "mistral"> =
	flattenClassifierModelCatalog("mistral", values);
