// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/moonshotai.json" with { type: "json" };

export const MOONSHOTAI_MODELS: ChatModelCatalog<typeof values, "moonshotai"> = flattenChatModelCatalog(
	"moonshotai",
	values,
);

export const MOONSHOTAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "moonshotai"> = flattenImageModelCatalog(
	"moonshotai",
	values,
);

export const MOONSHOTAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "moonshotai"> =
	flattenClassifierModelCatalog("moonshotai", values);
