// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/opencode-go.json" with { type: "json" };

export const OPENCODE_GO_MODELS: ChatModelCatalog<typeof values, "opencode-go"> = flattenChatModelCatalog(
	"opencode-go",
	values,
);

export const OPENCODE_GO_IMAGE_MODELS: ImageModelCatalog<typeof values, "opencode-go"> = flattenImageModelCatalog(
	"opencode-go",
	values,
);

export const OPENCODE_GO_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "opencode-go"> =
	flattenClassifierModelCatalog("opencode-go", values);
