// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/opencode.json" with { type: "json" };

export const OPENCODE_MODELS: ChatModelCatalog<typeof values, "opencode"> = flattenChatModelCatalog("opencode", values);

export const OPENCODE_IMAGE_MODELS: ImageModelCatalog<typeof values, "opencode"> = flattenImageModelCatalog(
	"opencode",
	values,
);

export const OPENCODE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "opencode"> =
	flattenClassifierModelCatalog("opencode", values);
