// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/openai-codex.json" with { type: "json" };

export const OPENAI_CODEX_MODELS: ChatModelCatalog<typeof values, "openai-codex"> = flattenChatModelCatalog(
	"openai-codex",
	values,
);

export const OPENAI_CODEX_IMAGE_MODELS: ImageModelCatalog<typeof values, "openai-codex"> = flattenImageModelCatalog(
	"openai-codex",
	values,
);

export const OPENAI_CODEX_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "openai-codex"> =
	flattenClassifierModelCatalog("openai-codex", values);
