// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/qwen-token-plan-cn.json" with { type: "json" };

export const QWEN_TOKEN_PLAN_CN_MODELS: ChatModelCatalog<typeof values, "qwen-token-plan-cn"> = flattenChatModelCatalog(
	"qwen-token-plan-cn",
	values,
);

export const QWEN_TOKEN_PLAN_CN_IMAGE_MODELS: ImageModelCatalog<typeof values, "qwen-token-plan-cn"> =
	flattenImageModelCatalog("qwen-token-plan-cn", values);

export const QWEN_TOKEN_PLAN_CN_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "qwen-token-plan-cn"> =
	flattenClassifierModelCatalog("qwen-token-plan-cn", values);
