// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";
import values from "./data/qwen-token-plan.json" with { type: "json" };

export const QWEN_TOKEN_PLAN_MODELS: ModelCatalog<typeof values, "qwen-token-plan"> = flattenModelCatalog(
	"qwen-token-plan",
	values,
);
