// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/radius.json" with { type: "json" };

export const RADIUS_MODELS: ChatModelCatalog<typeof values, "radius"> = flattenChatModelCatalog("radius", values);

export const RADIUS_IMAGE_MODELS: ImageModelCatalog<typeof values, "radius"> = flattenImageModelCatalog(
	"radius",
	values,
);

export const RADIUS_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "radius"> = flattenClassifierModelCatalog(
	"radius",
	values,
);
