// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/together.json" with { type: "json" };

export const TOGETHER_MODELS: ChatModelCatalog<typeof values, "together"> = flattenChatModelCatalog("together", values);

export const TOGETHER_IMAGE_MODELS: ImageModelCatalog<typeof values, "together"> = flattenImageModelCatalog(
	"together",
	values,
);

export const TOGETHER_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "together"> =
	flattenClassifierModelCatalog("together", values);
