// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/typesafe.json" with { type: "json" };

export const TYPESAFE_MODELS: ChatModelCatalog<typeof values, "typesafe"> = flattenChatModelCatalog("typesafe", values);

export const TYPESAFE_IMAGE_MODELS: ImageModelCatalog<typeof values, "typesafe"> = flattenImageModelCatalog(
	"typesafe",
	values,
);

export const TYPESAFE_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "typesafe"> =
	flattenClassifierModelCatalog("typesafe", values);
