// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/xai.json" with { type: "json" };

export const XAI_MODELS: ChatModelCatalog<typeof values, "xai"> = flattenChatModelCatalog("xai", values);

export const XAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "xai"> = flattenImageModelCatalog("xai", values);

export const XAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "xai"> = flattenClassifierModelCatalog(
	"xai",
	values,
);
