// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/xiaomi.json" with { type: "json" };

export const XIAOMI_MODELS: ChatModelCatalog<typeof values, "xiaomi"> = flattenChatModelCatalog("xiaomi", values);

export const XIAOMI_IMAGE_MODELS: ImageModelCatalog<typeof values, "xiaomi"> = flattenImageModelCatalog(
	"xiaomi",
	values,
);

export const XIAOMI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "xiaomi"> = flattenClassifierModelCatalog(
	"xiaomi",
	values,
);
