// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";
import values from "./data/zai-coding-cn.json" with { type: "json" };

export const ZAI_CODING_CN_MODELS: ModelCatalog<typeof values, "zai-coding-cn"> = flattenModelCatalog(
	"zai-coding-cn",
	values,
);
