// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import {
	type ChatModelCatalog,
	type ClassifierModelCatalog,
	flattenChatModelCatalog,
	flattenClassifierModelCatalog,
	flattenImageModelCatalog,
	type ImageModelCatalog,
} from "../model-catalog.ts";
import values from "./data/zai.json" with { type: "json" };

export const ZAI_MODELS: ChatModelCatalog<typeof values, "zai"> = flattenChatModelCatalog("zai", values);

export const ZAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "zai"> = flattenImageModelCatalog("zai", values);

export const ZAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "zai"> = flattenClassifierModelCatalog(
	"zai",
	values,
);
